#!/bin/sh

DEST="/Users/mark/docker/wordpress/wp-app/wp-content/plugins/vandergraaf"

if [ ! -d "$DEST" ]; then
	mkdir $DEST

	if [ ! -d "$DEST/js" ]; then
		mkdir $DEST/js
	fi

	if [ ! -d "$DEST/classes" ]; then
		mkdir $DEST/classes
	fi
else
	if [ ! -d "$DEST/js" ]; then
		mkdir $DEST/js
	fi

	if [ ! -d "$DEST/classes" ]; then
		mkdir $DEST/classes
	fi
fi

cp vandergraaf.php $DEST
cp vandergraaf-logo.png $DEST
sudo -u root /bin/cp classes/* $DEST/classes
cp js/vandergraaf.js $DEST/js/vandergraaf.js